name: Hello World Action
run-name: Demonstrate a simple GitHub Action

on:
  push:
    branches: [ 'hello_world', "test-branch" ]
  pull_request:
    branches: [ 'hello_world', "test-branch" ]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-22.04
    environment: "test_2"
    env:
      name: 'World'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Greet
        run: echo "Hello ${{ ENV.name }}!"

      - name: Ref name
        run: echo "${{ github.ref }}!"

  job2:
    name: Job 2
    runs-on: ubuntu-22.04
    steps:
      - name: Information
        run: |
          echo "This is an output of the second job."
          echo "Each job is performed inside distinct containers"
